version: 2

jobs:
  pr:
    working_directory: ~/repo
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - run:
          name: Update Conda
          command: |
            conda config --set always_yes True
            conda config --add channels conda-forge
            conda update --all
      - run:
          name: Git user
          command: |
            git config --global user.name regro-cf-autotick-bot
            git config --global user.email circleci@cf-graph.regro.github.com
      - run:
          name: Clone and Setup
          command: |
            export START_TIME=$(date +%s)
            export TIMEOUT=7200
            set -e
            git clone https://github.com/regro/cf-scripts.git
            cd cf-scripts
            export GIT_FULL_HASH=`git rev-parse HEAD`
            conda install python=3.6 conda=4.5
            conda install --file requirements/run
            python setup.py develop
            cd ..
            git clone --depth=1 https://github.com/regro/cf-graph.git
            cd cf-scripts
            export PATH=~/mc/bin:$PATH
            xonsh circle.xsh
workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
#          cron: "0 1,3,5,7,9,11,13,15,17,19,21,23 * * *"
          cron: "17 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - pr
